import {Smartphone} from "../../types/Smartphone";
import {Colors, Currency, Manufacturers} from "../../types";

import s10 from '../images/3.png';

export const smartphones: Smartphone[] = [
    {
        id: 1,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
    {
        id: 2,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
    {
        id: 3,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
    {
        id: 4,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
    {
        id: 5,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
    {
        id: 6,
        name: 'Samsung Galaxy S20',
        price: 999.99,
        currency: Currency.usd,
        color: Colors.black,
        image: s10,
        count: 10,
        manufacturer: Manufacturers.samsung,
        year: 2022,
        camera: 12,
    },
];
